language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tommydo/docker-react -f Dockerfile.dev . 

script:
  -  docker run -e CI=true tommydo/docker-react npm run test

deploy:
  provider: elasticbeanstalk # Travis comes preconfigured to deploy to a handful of providers 
  region: "us-east-2" # region that our app is hosted on. Can be found on web link
  app: "docker-react" # name of our app
  env: "Dockerreact-env" # app env
  bucket_name: "elasticbeanstalk-us-east-2-443571617150" # automatically created when setting up EB. Found under S3
  bucket_path: "docker-react" # default is name of the app
  on:
    branch: master # only trigger travis on pushes to master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY